name: Publish
on:
  push:
    tags:
      - v**
permissions:
  contents: write
jobs:
  publish:
    name: Publish Entities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 21
          cache: gradle
      - name: Make executable
        run: |
          chmod +x ./gradlew
      - name: Build
        env:
          USERNAME: ${{ secrets.USER }}
          TOKEN: ${{ secrets.TOKEN }}
        run: ./gradlew test build version publish createChangelog
      - name: Get version
        id: version
        run: |
          echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT
      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          version=${{ steps.version.outputs.version }}
          body=$(cat CHANGELOG.md)
          gh release create --draft "v$version" --title "v$version" --notes "$body"
      - name: Upload artifact
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          tag=${{ github.event.ref }}
          version=${{ steps.version.outputs.version }}
          gh release upload "v$version" "build/libs/entities-$version.jar"